pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                docker compose down
                docker compose pull
                docker compose up -d
                '''
            }
        }

    }
}