server {

    listen 80;

    server_name wordpress.example.com;

    location / {

        proxy_pass http://wordpress-app:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

    }

}